#+ summary: Find placenames in Maluku, Indonesia with geonamesID and coordinates
#+ endpoint: https://query.wikidata.org/sparql

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT * WHERE {
  ?place wdt:P131 wd:Q5093 ; # select places in Maluku, Indonesia
         wdt:P1566 ?gnID;   
         wdt:P625 ?_coordinates . 
}